server:
  port: 8080
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chatdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10  #初始化时建立物理连接的个数
    maxActive: 50    #最大连接池数量
    maxWait: 60000   #获取连接时最大等待时间
    poolPreparedStatements: true #是否缓存


mybatis:
  type-aliases-package: com.websocketapp.websocketapp.Mapper
  mapper-locations: classpath:mybatis/mappers/*.xml


logging:
  level:
    com.websocketapp.websocketapp.Mapper: debug